version = 0.1
[default.deploy.parameters]
stack_name = "products-catalog-lambda-app"
resolve_s3 = true
s3_prefix = "products-catalog-lambda-app"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []